package com.gousade.mapper;

import com.gousade.pojo.Trole;

public interface TroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    int insert(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    int insertSelective(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    Trole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trole record);
}